name: Build fzf for Debian

on:
  workflow_dispatch:
    inputs:
      fzf_version:
        description: The version of fzf to build.
        type: string
        required: true
      build_version:
        description: The build version.
        type: string
        required: true

permissions:
  contents: write

jobs:
  build-fzf:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout fzf-debian
        uses: actions/checkout@v4

      - name: Build fzf
        run: ./build.sh ${{ inputs.fzf_version }} ${{ inputs.build_version }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: fzf_*.deb


  release-fzf:
    name: (Draft-)Release fzf for Debian
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-fzf
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: fzf_*.deb
          name: ${{ inputs.fzf_version }}+${{ inputs.build_version }}
          tag_name: ${{ env.RELEASE_TAG }}
          fail_on_unmatched_files: true
